agents:
  queue: "public"

env:
  GO_VERSION_FILE: "go1.23.0.linux-amd64.tar.gz"


# Mount the docker.sock as to the docker container, so that we are able to
# run docker build command and kind is spawned as a sibling container.
steps:
  - group: "Upgrade Test"
    steps:
      - label: "Upgrade Test {{matrix}}"
        matrix:
          - "1.31.0"
          - "1.30.4"
          - "1.29.8"
        command:
        - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
        - wget https://golang.org/dl/$GO_VERSION_FILE
        - tar -C /usr/local -xzf $GO_VERSION_FILE
        - export PATH=$PATH:/usr/local/go/bin
        - rm $GO_VERSION_FILE
        - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
        - K8S_VERSION={{matrix}} make upgrade-test
        concurrency: 1
        concurrency_group: 'vtop/upgrade-downgrade-test'
        timeout_in_minutes: 60
        plugins:
          - docker#v3.12.0:
              image: "docker:latest"
              propagate-environment: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"

  - group: "Backup Restore Test"
    steps:
      - label: "Backup Restore Test {{matrix}}"
        matrix:
          - "1.31.0"
          - "1.30.4"
          - "1.29.8"
        command:
        - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
        - wget https://golang.org/dl/$GO_VERSION_FILE
        - tar -C /usr/local -xzf $GO_VERSION_FILE
        - export PATH=$PATH:/usr/local/go/bin
        - rm $GO_VERSION_FILE
        - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
        - K8S_VERSION={{matrix}} make backup-restore-test
        concurrency: 1
        concurrency_group: 'vtop/backup-restore-test'
        timeout_in_minutes: 60
        plugins:
          - docker#v3.12.0:
              image: "docker:latest"
              propagate-environment: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"

  - group: "Backup Schedule Test"
    steps:
      - name: "Backup Schedule Test {{matrix}}"
        matrix:
          - "1.31.0"
          - "1.30.4"
          - "1.29.8"
        command:
          - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
          - wget https://golang.org/dl/$GO_VERSION_FILE
          - tar -C /usr/local -xzf $GO_VERSION_FILE
          - export PATH=$PATH:/usr/local/go/bin
          - rm $GO_VERSION_FILE
          - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
          - K8S_VERSION={{matrix}} make backup-schedule-test
        concurrency: 1
        concurrency_group: 'vtop/backup-schedule-test'
        timeout_in_minutes: 60
        plugins:
          - docker#v3.12.0:
              image: "docker:latest"
              propagate-environment: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"

  - group: "VTOrc and VTAdmin Test"
    steps:
      - label: "VTOrc and VTAdmin Test {{matrix}}"
        matrix:
          - "1.31.0"
          - "1.30.4"
          - "1.29.8"
        command:
        - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat chromium
        - wget https://golang.org/dl/$GO_VERSION_FILE
        - tar -C /usr/local -xzf $GO_VERSION_FILE
        - export PATH=$PATH:/usr/local/go/bin
        - rm $GO_VERSION_FILE
        - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
        - K8S_VERSION={{matrix}} make vtorc-vtadmin-test
        concurrency: 1
        concurrency_group: 'vtop/vtorc-vtadmin-test'
        timeout_in_minutes: 60
        plugins:
          - docker#v3.12.0:
              image: "docker:latest"
              propagate-environment: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"

  - group: "Unmanaged Tablet Test"
    steps:
      - label: "Unmanaged Tablet Test {{matrix}}"
        matrix:
          - "1.31.0"
          - "1.30.4"
          - "1.29.8"
        command:
        - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat chromium
        - wget https://golang.org/dl/$GO_VERSION_FILE
        - tar -C /usr/local -xzf $GO_VERSION_FILE
        - export PATH=$PATH:/usr/local/go/bin
        - rm $GO_VERSION_FILE
        - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
        - K8S_VERSION={{matrix}} make unmanaged-tablet-test
        concurrency: 1
        concurrency_group: 'vtop/unmanaged-tablet-test'
        timeout_in_minutes: 60
        plugins:
          - docker#v3.12.0:
              image: "docker:latest"
              propagate-environment: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
