agents:
  queue: "public"

env:
  GO_VERSION_FILE: "go1.23.5.linux-amd64.tar.gz"

# Mount the docker.sock as to the docker container, so that we are able to
# run docker build command and kind is spawned as a sibling container.
steps:
  - name: "Backup Restore Test"
    command:
    - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat doas
    - export PATH=$PATH:/usr/local/go/bin:/sbin:/usr/sbin:/bin
    - adduser -D -u 1001 vitess
    - adduser vitess wheel
    - echo 'permit nopass :wheel' > /etc/doas.d/doas.conf
    - wget https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - doas make backup-restore-test
    concurrency: 1
    concurrency_group: 'vtop/backup-restore-test'
    timeout_in_minutes: 60
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
